
DROP TABLE IF EXISTS user_table CASCADE;
DROP TABLE IF EXISTS role_table CASCADE;
DROP TABLE IF EXISTS user_role_table CASCADE;
DROP TABLE IF EXISTS advertisement CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;